MERGE INTO FILM (ID, NAME, DESCRIPTION, RELEASEDATE, DURATION, MPA) KEY(ID)
VALUES (2, 'ALIEN', 'Interesting film', '1986-10-11', 120, 'PG_13');

MERGE INTO FILM (ID, NAME, DESCRIPTION, RELEASEDATE, DURATION, MPA) KEY(ID)
    VALUES (4, 'HARRY POTTER', 'Magic film', '2002-10-11', 120, 'G');

MERGE INTO USER_FILMORATE (ID, EMAIL, LOGIN, NAME, BIRTHDAY) KEY(ID)
    VALUES (5, 'someEmail@gmail.com', 'someLogin', 'Nikolay', '1983-10-11');

MERGE INTO USER_FILMORATE (ID, EMAIL, LOGIN, NAME, BIRTHDAY) KEY(ID)
    VALUES (6, 'someAnotherEmail@gmail.com', 'TestLogin', 'Maxim', '1954-10-11');

MERGE INTO USER_FILMORATE (ID, EMAIL, LOGIN, NAME, BIRTHDAY) KEY(ID)
    VALUES (7, 'someAnotherEmail@gmail.com', 'TestLogin', 'Erick', '1976-10-11');