CREATE TABLE IF NOT EXISTS USER_FILMORATE
(
    id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email    varchar(50),
    login    varchar(50),
    name     varchar(50),
    birthday DATE
);

CREATE TABLE IF NOT EXISTS SUBSCRIBER_STATUS
(
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    userId           INTEGER REFERENCES USER_FILMORATE (id) ON DELETE CASCADE,
    subscriberId     INTEGER,
    friendshipStatus ENUM (
        'FRIEND',
        'SUBSCRIBER'
        )
);

CREATE TABLE IF NOT EXISTS FILM
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        varchar(50),
    description varchar(2000),
    date_prod   DATE,
    duration    LONG,
    mpa         varchar(10)
);

CREATE TABLE IF NOT EXISTS FILM_LIKES
(
    id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    filmId INTEGER REFERENCES FILM (id) ON DELETE CASCADE ,
    userId INTEGER
);

CREATE TABLE IF NOT EXISTS FILM_GENRE
(
    id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    filmId INTEGER REFERENCES FILM (id),
    genre  ENUM (
        'COMEDY',
        'DRAMA',
        'CARTOON',
        'THRILLER',
        'DOCUMENTARY',
        'ACTION'
        )
);

CREATE TABLE IF NOT EXISTS MPA
(
    id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mpa    ENUM (
           'G', 'PG', 'PG-13', 'R', 'NC-17'
        )
);

CREATE TABLE IF NOT EXISTS GENRE
(
    id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    genre  ENUM (
        'COMEDY',
        'DRAMA',
        'CARTOON',
        'THRILLER',
        'DOCUMENTARY',
        'ACTION'
        )
)

