CREATE TABLE IF NOT EXISTS USER_FILMORATE
(
    id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email    varchar(50),
    login    varchar(50),
    name     varchar(50),
    birthday DATE,
    friendsIds OBJECT
);

CREATE TABLE IF NOT EXISTS SUBSCRIBER_STATUS
(
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    userId           INTEGER REFERENCES USER_FILMORATE (id) ON UPDATE RESTRICT,
    subscriberId     INTEGER,
    friendshipStatus ENUM (
        'FRIEND',
        'SUBSCRIBER'
        )
);

CREATE TABLE IF NOT EXISTS FILM
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        varchar(50),
    description varchar(2000),
    releaseDate DATE,
    duration    LONG,
    userLike    OBJECT,
    genre       OBJECT,
    mpa         ENUM (
        'G',
        'PG',
        'R',
        'PG_13',
        'NC_17'
        )
);

CREATE TABLE IF NOT EXISTS FILM_LIKES
(
    id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    filmId INTEGER REFERENCES FILM (id) ON UPDATE RESTRICT,
    userId INTEGER
);

CREATE TABLE IF NOT EXISTS FILM_GENRE
(
    id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    filmId INTEGER REFERENCES FILM (id) ON UPDATE RESTRICT,
    genre  ENUM (
        'COMEDY',
        'DRAMA',
        'CARTOON',
        'THRILLER',
        'DOCUMENTARY',
        'ACTION'
        )
)

